# Generated by Django 2.1.5 on 2021-02-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='Descripcion'),
        ),
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(default='Titulo', max_length=20),
        ),
    ]
